### ISSUE TITLE
Stackoverflow error

### ISSUE THREAD

**Issue by LarpinMartin** [Diamssword/TesseraktMod#4]
Mekanism mod piping out brine from a tower into a tesserakt causes the server to crash. Rebooting the server does not fix this issue and as a result I had to remove the mod.

java.lang.StackOverflowError: null at com.diamssword.tesserakt.storage.TileFLuidStorage$1.canFillFLuidType(TileFluidStorage.java:97) ~[TileFluidStorage$1.class:?]

**Comment by Diamssword** [comment]
Thanks for the report, I will look into that

**Comment by Diamssword** [comment]
Should be fixed with the new version avaiable on CurseForge!
